apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        args: ["--datadir", "/data/db"]
        envFrom:
          - configMapRef:
              name: mysql-config
          - secretRef:
                name: mysqlsecret 
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - mountPath: /data/db
            name: mysql-volume  
      volumes:
        - name: mysql-volume
          hostPath:
              path: /data 
      
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30018
  selector:
    app: mysql
  type: NodePort
